server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  # Mail Configuration (for email notifications)
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: ahafxzlryxrnxsqq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

notification:
  service:
    email:
      from: noreply@ecommerce.com
      enabled: true
    sms:
      enabled: false
      provider: twilio